### ISSUE TITLE
RSVP Approval improvements

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13240]
This is a list of improvements we can make for RSVPs once the MVP is out:

* [x] A future flow will include bulk approval/denial. https://github.com/unlock-protocol/unlock/issues/13864
* [x] We also need to resolve an issue with pagination (in a follow up PR). This should also fix https://github.com/unlock-protocol/unlock/issues/12937
* [x] Refactor so we can auto-reload the Members lists https://github.com/unlock-protocol/unlock/issues/12989
* [x] RSVP for event, rather than contract centric (let organizer chose which contract they want to airdrop for)
* [x] Toggle setting for approval required
* [x] Lock picker in airdrop https://github.com/unlock-protocol/unlock/issues/13216
* [x] Clarify what image is used where and how to update them!
