### ISSUE TITLE
Create Unlock Provider as part of unlock-js

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#2414]
- [x] Create provider middleware to manage initialization of providers (#2470)
- [x] Integrate provider middleware with app (#2487)
- [ ] Build and test Unlock Provider to match spec document (not yet public)

**Comment by julien51** [comment]
Turning this into an Epic to keep track of it more easily (it stays inside User Account and unlock-js library epics too!)
