### ISSUE TITLE
Be able to log in to an account

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#2721]
Currently it is possible (in development) to create an account. However, there is no way to log in to an account, which makes the account dubiously useful at best.

- [x] Page to log in from
- [x] Link to that page/state from the sign up page, which is the default if there is no account
- [x] Use storage service to authenticate and put the account into state
