### ISSUE TITLE
Further slicing and dicing of #3546 (open sub-issues as needed)

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3549]
This is a multi-step process slicing and dicing #3546:

These can all be done in parallel and do not conflict with one another beyond rebasing:

1. [x] PR (1) extract `web3ServiceHub` and write tests
2. [x] PR (2) pass in `window` and `locksmithHost` to `processKeyPurchaseTransactions` (`purchaseKey.js`), `setupWeb3Service` (`blockchainHandler/index.js`), `makePurchaseCallback` (`makePurchaseCallback.js`), `connectToBlockchain` (`connectToBlockchain.js`) in preparation for enabling the `web3ServiceHub`. Convert`locksmithTransactions` function to accept { params } instead of param, param (`locksmithTransactions.js`) and modify `retrieveData` in `blockchainHandler/index.js` to wrap the passed params in {}
3. [x] PR (3) grab `storeTransaction` from `locksmithTransactions.js`, add new tests for it
4. [x] PR (4) remove `getSetConfigCallback` from `blockchainHandler/index.js` and its tests (unused function)

After these are merged, these can all be done in parallel:

1. [x] PR (5) refactor `processKeyPurchaseTransactions` to remove `updateListener`, as `web3ServiceHub` will handle this, delete `updateListener.js` and its test
2. [ ] PR (6) refactor `locksmithTransactions` to remove any transaction retrieval or return and instead just call `web3Service.getTransaction` to start the polling (these are the changes in the bottom of `locksmithTransactions.js`
3. [x] PR (7) enable `web3ServiceHub` inside `setupWeb3Service` in `blockchainHandler/index.js`
4. [x] PR (8) remove returning transaction data from `retrieveChainData` in `blockchainHandler/index.js` (the updates are done by `web3ServiceHub`

That's it!

**Comment by cellog** [comment]
fixed!
