### ISSUE TITLE
App-side changes for user account key purchase

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4164]
Tracking needed changes on the app side of a user account key purchase.

- [x] CSS for iframe (white background, sizing). A stopgap for convenience is acceptable at this juncture
- [x] Changing login component to allow account creation more easily (opening new tab will cause issues with next on local dev - figure out an alternative)
- [x] Getting locks - can't just add to cart on receiving UPDATE_LOCKS. Ask @cellog  if we can change it so KEY_PURCHASE passes the whole lock under consideration (minimizes state and logic within unlock-app)
- [x] show actual key price on confirmation component (currently hardcoded)
- [ ] Make container for embed elastic, so that it is only as big as it needs to be for the current step. Currently it grows in height if needed, but can be improved.
- [x] Make various components more like the Figma designs (https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Paywall?node-id=0%3A817)
  - [x] Log in
  - [x] Sign up? Not sure if we're going with the Figma design on this one
  - [x] Credit card form _(I think @benwerd  is taking this one)_
  - [x] Purchase confirmation (_claimed_)
  - [x] add an X at the top of the embed to dismiss
- [x] Correctly log in immediately after successful signup
