### ISSUE TITLE
User accounts CSS meta-issue

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4367]
This issue tracks a few issues relating to how user accounts-related components render on different browsers.

- [ ] Button text not centered on account settings page
  <img width="454" alt="image" src="https://user-images.githubusercontent.com/9300702/62629644-95245880-b8fb-11e9-955a-c75db5452c0b.png">
- [ ] Stripe components not consistent with other inputs
  - Cursor larger, no highlight when field is focused
  - Not sure how much control we have over these
<img width="454" alt="image" src="https://user-images.githubusercontent.com/9300702/62629756-c8ff7e00-b8fb-11e9-9195-2897e40470fd.png">

- [ ] Key purchase confirmation is too narrow and button text not centered

<img width="454" alt="image" src="https://user-images.githubusercontent.com/9300702/62629910-0a902900-b8fc-11e9-9d71-0d1a8b751314.png">
