### ISSUE TITLE
Upgrade all react subrepos to use @testing-library/react

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5161]
We've been a few releases behind. We should incrementally update each subrepo until we've purged the last remnants of `react-testing-library`.

- [x] unlock-app (done in #5158)
- [x] paywall (done in #5164)
- [x] tickets (done in #5162)
- [x] unlock-protocol.com (done in #5163)
