### ISSUE TITLE
Hook up new BlockchainHandler in parallel on unlock.js script in paywall

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5428]
With #5417 and #5427 we have enough pieces to trial the new data iframe in parallel with the existing one.

To do this, we'll need a few different things:

- [x] Get the new BlockchainHandler to build and be served in such a way that we can load an iframe into it (#5433)
- [x] define a postmate `Child` for the BlockchainHandler (#5433)
- [ ] define a postmate `Parent` for the main window (in progress at #5436)

Once we have these in, we can start handling some pieces of the app's needs with the new handler. Unfortunately there may be downstream changes required (checkout iframe currently relies on some of the old behavior of the data iframe).

I think once these pieces are in place it should be easy to quickly iterate on this junction and it will give us a template to follow in hooking up the other iframes and moving to our new desired architecture.
