### ISSUE TITLE
Signing meta-data fails in MetaMask

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6640]
We have identifed that signing metadata currently fails on MetaMask.
1. [X] We should not fail silently
2. [x] We should fix it
3. [X] We should add a check in the prod deploy flow.
