### ISSUE TITLE
Epic: Ticket checkin refactored!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8663]
This is going to be a big refactor for the ticketing use-case of Unlock. We may open smaller Github issues for items that deserve it and we should definitely open multiple small Pull Requests to cover this.

**The overarching goal is to improve our ticket's check-in experience.**

For reference, here is the current flow: 
1. The user goes to the keychain and clicks on the icon to generate a QR code for a specific key
2. They sign a message
3. This displays a QR code that can be scanned by anyone
4. The Verification page is loaded and shows info about the ticket, including whether it has been verified _previously_.
5. If the scanner is a lock manager and the ticket has not been verified previously, they can click a button to "mark as checked-in".
6. If the lock manager clicks the button, they are prompted to sign a message 
7. Ticket is marked as checked-in in our data store.

We want to take the same flow but improve multiple aspects and reduce friction.

## Adding the "verifier" role

The first step is to add the role of "verifier". The goal of this new role is to avoid requiring the "admin" role of lock manager for people who are marking tickets as checked in. 
To do this, we will have to perform the following things:
* [x] Add a verifier table to locksmith database with the following fields: `address`, `lockAddress`, `network` (for the lock), `lockManager` (address of the lock manager that granted that role), `createdAt`.
* [x] Add an API endpoint for a lock manager to list all verifiers for a specicifc lock address
* [x] Add an API endpoint for a lock manager to add a verifier to a lock
* [x] Add an API endpoint for a lock manager to remove a verifier for a lock
* [x] Add a new page on the `unlock-app` that will provide a UI to list, add and remove verifier for a specific lock. This page will be at `/verifiers?lockAddress=0x....` and will use the SIWE authentication to only show data to a lock manager.
All of these API endpoints must use the v2 auth framework implemented by @searchableguy  (SIWE).

## Signature of tickets/NFT is done by locksmith

In order to simplify the user flows, we want to add the ability to send the QR codes to users without requiring them to connect to the keychain first. As such, we need to : 
* [x] add an API endpoint to locksmith that will generate a signature for a payload that can be used to create ticket QR code  for a specific lock address and a specific token id. This API can only be called by the specific key owner.
* [x] #9053
* [ ] #9031

## Allowing Verification of tickets signed by locksmith's purchaser address

Right now, the verification only succeeds if the signer is the owner of the NFT. 
* [x] Add a new endpoint to locksmith that marks a ticket/key as checked in. It can only be called by a verifier (auth error otherwise)
* [x] We should make it succeed if the signer is _either_ the owner of the NFT or the locksmith's purchaser address.
* [ ] Additionally the signed message should include the token Id, as we now support owning multiple tokens per address.

## Use of SIWE for check-in

Finally, we should update the verification app with the following:

* [x] Includes @searchableguy 's new SIWE integration in order to avoid asking the verifier to sign messages over and over. Make sure the "Mark as checked-in button" is functional for Lock Manager and Verifiers.
* [x]  if the user loading the application is a verifier and/or lock manager, load and show the metadata associated with the key and the owner's address (as shown on the member list UI)
* [x] per @ccarfi suggestion: show the actual NFT image

**Comment by julien51** [comment]
@ChialiTsai I am not sure we need to do very significant design changes, but please let me know if you disagree!

**Comment by julien51** [comment]
About https://github.com/unlock-protocol/unlock/pull/9031 I am actually not sure we should do it anymore.
It's actually pretyu useful to have users be able to sign themselves...
